# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  clean:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:16.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
        
      # run coverage!
      - run: mvn clean
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:16.0

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout
        
      # run tests!
      - run: mvn integration-test

workflows:
  version: 2
  clean_build:
    jobs:
      - clean
      - build:
          requires:
            - clean