=== Example Code
Now you are ready to run a first "Hello World" project.

. We called it +HelloEdison+ in the package +tec.uom.demo.edison.hello+
. The following code: 
+
[source,java]
----
        System.out.println("Hello Edison.");
        System.out.println("How about a little lightbulb efficiency calculation?;-)");
        final MessageFormat question = new MessageFormat(
                "What is the power consumption of a lamp that has luminous flux of {0} and luminous efficacy of {1} lumens per watt (lm/W)?");
        final MessageFormat answer = new MessageFormat("You need a {0} lightbulb.");
        
        Quantity<LuminousFlux> lm = Quantities.getQuantity(900, SI.LUMEN);
        final Unit<LuminousEfficacy> LM_PER_WATT = SI.LUMEN.divide(SI.WATT).asType(LuminousEfficacy.class);
        final Number LM_VALUE = 15;
        final Object[] questionArgs = {lm, LM_VALUE};
        System.out.println(question.format(questionArgs));
        Quantity<LuminousEfficacy>  luminousEfficacy = Quantities.getQuantity(LM_VALUE, LM_PER_WATT);
        Quantity<Power> p = lm.divide(luminousEfficacy).asType(Power.class);
        final Object[] answerArgs = {p};
        System.out.println(answer.format(answerArgs));
----
+
Calculates which light bulb you need to produce a certain "brightness".
The units of these parameters are not defined; just that they are of quanity +Mass+ and +Acceleration+ respectively.
+
So our code needs to get the absolute value of these in a known unit for calculation - for simplicity we use the SI units Kilogram (kg) and Metres per second per second (m/s2).
We then simply perform the multiplication, and create a result using the SI unit for Force - Newtons (N).

. Now we have our example API implementation - we need to call it to see it do something. Let's create a unit test. (OK purists, we should have created this first to be truly TDD, but this is just a tutorial!)
